server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    # 最大吞吐量不限制
    max-swallow-size: -1
  # 优雅停机 关闭容器后默认等待30秒继续执行没处理完的任务 避免数据不一致
  shutdown: graceful

spring:
  lifecycle:
    # 配置优雅停机后的缓冲器 最大等待时间
    timeout-per-shutdown-phase: 10s
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hiver?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 1qazxsw2#
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: 1qazxsw2#
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      filter:
        stat:
          # 开启监控sql
          enabled: true
          # 显示并标注慢sql 默认当超过3秒显示
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        # 防SQL注入过滤
        wall:
          config:
            # 允许多条sql同时执行
            multi-statement-allow: true

logging:
  level:
    mybatis.meta: debug

# springdoc-openapi配置
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: '1.HiverX管理接口 v1.0'
      paths-to-exclude: '/hiver/app/**'
      packages-to-scan: plus.hiver
    - group: '2.HiverX APP接口 v1.0'
      paths-to-match: '/hiver/app/**'
      packages-to-scan: plus.hiver
  default-flat-param-object: true

# 接口文档增强UI Swagger界面内容配置
knife4j:
  enable: true

swagger:
  title: HiverX API接口文档
  description: HiverX Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://hiver.plus
  contact:
    name: Nein
    url: https://hiver.plus
    email: delicacylee@vip.sina.com

# 框架前缀
hiver:
